-- AlterTable
ALTER TABLE "Wallet" ALTER COLUMN "balance" SET DEFAULT 100,
ALTER COLUMN "balance" SET DATA TYPE BIGINT,
ALTER COLUMN "onHand" SET DEFAULT 0,
ALTER COLUMN "onHand" SET DATA TYPE BIGINT,
ALTER COLUMN "loan" SET DEFAULT 0,
ALTER COLUMN "loan" SET DATA TYPE BIGINT;
