import { cryptoRandRange } from './qrng';

const random = cryptoRandRange;

export const weapons = [
    { name: 'their fists', damage: () => random(0, 5) },
    { name: 'a shank', damage: () => random(4, 10) },
    { name: 'some brass knuckles', damage: () => random(3, 8) },
    { name: 'a chainsaw', damage: () => random(10, 20) },
    { name: "Sami's Feather", damage: () => random(5, 15) },
    { name: 'the TVA Stick', damage: () => random(15, 25) },
    { name: 'a pool noodle', damage: () => random(1, 4) },
    { name: 'their head', damage: () => random(0, 10) },
    { name: 'the power of R.N.Jesus', damage: () => random(-200, 50) },
    { name: 'a Splash Potion of Harming', damage: () => random(10, 30) },
    { name: "an Asian Person's Corpse", damage: () => random(5, 10) },
    { name: 'a Comically Large Spoon', damage: () => random(20, 35) },
    { name: 'a North Korean Special Agent tasked with watching the American tourists', damage: () => random(10, 45) },
    { name: 'a healing potion', damage: () => random(-40, -1) },
    { name: 'a B-2 Bomber', damage: () => random(50, 60) },
    { name: 'a　宇う酒です～ ！！！！！！！！！', damage: () => random(-100, 100) },
    { name: 'the seven layers of hell', damage: () => random(10, 70) },
    { name: 'a free ticket for the other person to win', damage: () => random(-1000, -1) },
    { name: 'a Mundane Potion', damage: () => random(-10, 10) },
    { name: 'the power of annoyance', damage: () => random(-5, 15) },
    { name: 'the redirected wrath invoked from pinging Haladesh', damage: () => random(50, 100) },
    { name: 'Cacher (when he is angry)', damage: () => random(10, 50) },
    { name: "Reality's Edge", damage: () => random(0, 10) },
    { name: "Tampered's Zweihander", damage: () => random(15, 30) },
    { name: 'the Crucible', damage: () => random(30, 150) },
    { name: 'The Hand of the King', damage: () => random(20, 50) },
    { name: 'a sausage', damage: () => random(1, 40) },
    { name: 'a Steel Sword', damage: () => random(1, 100) },
    { name: 'ぞ', damage: () => random(10, 90) },
    { name: 'R.N.Hellus', damage: () => random(-50, 100) },
    { name: 'spam', damage: () => random(0, 25) },
    { name: 'an Evoker', damage: () => random(25, 51) },
    { name: 'overrated and overused ROBLOX music', damage: () => random(10, 25) },
    { name: 'the Legendary Power of JEFF', damage: () => random(10, 45) },
    { name: 'literally nothing', damage: () => 0 },
    { name: 'their liver', damage: () => 15 },
    { name: "some staff member's Ban Hammer", damage: () => random(50, 75) },
    { name: '-bonk', damage: () => random(0, 25) },
    { name: "Spy's Naginata", damage: () => random(20, 40) },
    { name: 'Frostmourne', damage: () => random(30, 40) },
    { name: 'bread', damage: () => random(1, 10) },
    { name: 'a piece of paper', damage: () => random(1, 2) },
    { name: 'a piece of cheese', damage: () => random(1, 5) },
    { name: 'a dragon', damage: () => random(20, 50) },
    { name: "verz's diet pepsi can", damage: () => random(5, 15) },
    { name: 'Uranium-235', damage: () => Infinity },
    { name: 'their tits', damage: () => Infinity }, // sho's suggestion not mine!
    { name: 'slurp juice', damage: () => random(-500, -50) },
    { name: 'https://cdn.discordapp.com/attachments/865305980627320862/920663807225888768/UAAAAAAAAA_.mp4', damage: () => random(70, 200) },
    { name: 'an ear of corn', damage: () => random(15, 20) },
    { name: 'exploding coca cola bottle', damage: () => random(50, 65) },
    { name: "Sho's .408 Cheytac Intervention", damage: () => 100 },
    { name: 'their IQ', damage: () => random(-150, 150) },
    { name: 'https://tenor.com/view/cat-long-neck-cat-funny-cat-wtf-cat-silly-cat-car-gif-21111587', damage: () => random(50, 60) },
    { name: 'https://tenor.com/view/rip-bozo-gif-22294771', damage: () => random(35, 55) },
    { name: 'https://tenor.com/view/pack-watch-snow-watch-gif-23787702', damage: () => random(15, 35) },
    { name: "the red imposter's knife", damage: () => random(10, 50) },
    { name: "Maige's Affection", damage: () => random(50, 75) },
    { name: 'The Keyblade', damage: () => random(30, 70) },
    { name: 'JJSploit Premium', damage: () => random(20, 50) },
    { name: 'an electrified bath', damage: () => random(46, 57) },
    { name: 'p', damage: () => random(20, 99) },
    { name: 'cat bread', damage: () => 68 },
    { name: "Cactus' broken keyboard", damage: () => random(10, 15) },
    { name: "Cactus' Super Golf skill", damage: () => random(3, 5) },
    { name: 'Comedy', damage: () => 69 },
    { name: 'an e-girl profile picture', damage: () => random(-100, -10) },
    { name: 'Calamity', damage: () => random(75, 100) },
    { name: "Tampered's anti-exploit", damage: () => random(100, 1000) },
    { name: 'a fish', damage: () => random(10, 25) },
    { name: 'a rock', damage: () => random(5, 15) },
    { name: 'a pillow', damage: () => random(1, 5) },
    { name: 'their arms to give their opponent a hug', damage: () => 0 },
    { name: "Tampered's rubber sandals", damage: () => random(150, 300) }
];

export const districts: { [key: number]: string } = {
    1: 'Luxury',
    2: 'Masonry and Defense',
    3: 'Technology',
    4: 'Fishing',
    5: 'Power',
    6: 'Transportation',
    7: 'Lumber',
    8: 'Textiles',
    9: 'Grain',
    10: 'Livestock',
    11: 'Agriculture',
    12: 'Coal',
    13: 'Nuclear Weaponry',
    14: 'Skill Issue'
};
